### ISSUE TITLE
必須画面の見た目をモックで全て作り上げる

### ISSUE THREAD

**Issue by NAKKA-K** [NAKKA-K/musclers#172]
# 概要

必須画面の見た目をモックで全て作り上げる。
画面それぞれにissueを立てる。

#### 必須

- [x] DM一覧画面: `/direct_messages` #148 
- [x] DM詳細画面: `/direct_messages/:id` #149 

- [x] グループの一覧画面: `/groups` #181 
- [x] グループの詳細画面: `/groups/:id` #183 
- [x] グループの作成画面: `/groups/new` #187 

- [x] ~所属グループのチャット一覧: `/group_messages`~ #200 
- [x] ある所属グループのチャット画面: ~`/group_messages/:id`~ -> `/groups/:id` #196 

- [x] グループの検索画面: `/groups/search` #230 

---
#### 追加だけど必須

- [x] ユーザーブログページ一覧: `/user_blogs` #205 
- [x] ユーザーブログページ詳細: `/user_blogs/:id` #228 

---
#### あると良い

- [x] 問い合わせページ(googleform): チームドライブの重要ディレクトリ内
- #250 

# モック・スクリーンショット

新規機能に関するモックやスクリーンショット(AdobeXDで作成した画面等)があれば添付

# 関連issue

- #138 このissueを参考にまだフロントができていないページを見繕う
- #169 追加されたモックはこちら
- #250 リリース時に必要な画面タスクはこちらに移動

# 留意事項・参考

留意事項や参考があれば

**Comment by NAKKA-K** [comment]
グループ検索画面は重要項目の中でも優先度が低めなので一旦置いておこう。
そして「あると良い」ページは一旦スルーで。
と言いたいところだけど、ユーザーブログページをどうするかなってのは少し迷っている。

**Comment by NAKKA-K** [comment]
今必要なのは完成
