### ISSUE TITLE
APIのテストをかく

### ISSUE THREAD

**Issue by kageyasai2** [NAKKA-K/musclers#215]
# 概要

作成したAPIの内、テストを書いていないAPIのテストを書いていく

テストを書いてないAPI一覧
- [x] ~tag list api #217~
- [x] ~user tag api #224~
- [x] ~search user api #226~
- [x] ~detail user api #237~
- [x] ~user data update api #246~
- [x] ~user data edit api #249~

# モック・スクリーンショット

新規機能に関するモックやスクリーンショット(AdobeXDで作成した画面等)があれば添付

# 関連issue

- [ ] あればissue番号を

# 留意事項・参考

とりあえず一人で頑張ってみる

**Comment by kageyasai2** [comment]
The End
